import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const projectRoot = process.cwd();
const staticRoot = path.join(projectRoot, "static");
const outputRoot = path.join(staticRoot, "_optimized");
const manifestPath = path.join(projectRoot, "data", "optimizedImages.json");
const targetWidths = [640, 960, 1600];
const supportedExtensions = new Set([".jpg", ".jpeg", ".png", ".webp"]);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    if (entry.name === "_optimized") continue;

    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await walk(absolutePath));
    } else if (supportedExtensions.has(path.extname(entry.name).toLowerCase())) {
      files.push(absolutePath);
    }
  }

  return files;
}

function toUrl(relativePath) {
  return `/${relativePath.split(path.sep).join("/")}`;
}

await rm(outputRoot, { recursive: true, force: true });
await mkdir(outputRoot, { recursive: true });
await mkdir(path.dirname(manifestPath), { recursive: true });

const manifest = {};
let sourceBytes = 0;
let optimizedBytes = 0;
let optimizedFiles = 0;

for (const sourcePath of await walk(staticRoot)) {
  const image = sharp(sourcePath, { animated: false, failOn: "none" });
  const metadata = await image.metadata();

  if (!metadata.width || !metadata.height || (metadata.pages || 1) > 1) continue;

  const relativePath = path.relative(staticRoot, sourcePath);
  const extension = path.extname(relativePath);
  const basePath = relativePath.slice(0, -extension.length);
  const widths = [...new Set(targetWidths.map((width) => Math.min(width, metadata.width)))].sort((a, b) => a - b);
  const variants = [];

  sourceBytes += (await stat(sourcePath)).size;

  for (const width of widths) {
    const outputRelativePath = `${basePath}-${width}.webp`;
    const outputPath = path.join(outputRoot, outputRelativePath);
    await mkdir(path.dirname(outputPath), { recursive: true });

    const info = await sharp(sourcePath, { animated: false, failOn: "none" })
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 82, effort: 4, smartSubsample: true })
      .toFile(outputPath);

    variants.push({ width: info.width, url: toUrl(path.join("_optimized", outputRelativePath)) });
    optimizedBytes += info.size;
    optimizedFiles += 1;
  }

  const largest = variants.at(-1);
  manifest[toUrl(relativePath)] = {
    width: metadata.width,
    height: metadata.height,
    src: largest.url,
    variants,
  };
}

await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Optimized ${Object.keys(manifest).length} images into ${optimizedFiles} WebP variants.`);
console.log(`Source bytes: ${sourceBytes}; generated bytes: ${optimizedBytes}.`);
